### ISSUE TITLE
使用 homebrew 安装的 lean-cli 在执行 lean deploy 命令时出错

### ISSUE THREAD

**Issue by idy** [leancloud/lean-cli#80]
```
➜  deploy git:(master) lean deploy
> 获取应用信息 [SUCCESS]
> 准备部署至目标应用：xxxx
> 获取应用分组信息 [SUCCESS]
> 准备部署应用到预备环境
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
       	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x356f]

goroutine 1 [running]:
panic(0x3bcfe0, 0xc420014130)
       	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
github.com/leancloud/lean-cli/lean/vendor/github.com/codegangsta/cli.HandleAction.func1(0xc420127928)
       	/private/tmp/lean-cli-20160825-86020-ielkme/lean-cli-0.2.0/src/github.com/leancloud/lean-cli/lean/vendor/github.com/codegangsta/cli/app.go:476 +0x29e
panic(0x3bcfe0, 0xc420014130)
       	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:458 +0x243
main.uploadProject(0xc420019410, 0x21, 0x42359c, 0x1, 0xc420127380, 0x64c67, 0x5e9de0)
       	/private/tmp/lean-cli-20160825-86020-ielkme/lean-cli-0.2.0/src/github.com/leancloud/lean-cli/lean/deploy_action.go:68 +0x11f
main.deployFromLocal(0xc420019410, 0x21, 0xc420423098, 0x7, 0x0, 0x0)
       	/private/tmp/lean-cli-20160825-86020-ielkme/lean-cli-0.2.0/src/github.com/leancloud/lean-cli/lean/deploy_action.go:95 +0x6c
main.deployAction(0xc4200a4640, 0x0, 0x0)
       	/private/tmp/lean-cli-20160825-86020-ielkme/lean-cli-0.2.0/src/github.com/leancloud/lean-cli/lean/deploy_action.go:163 +0x2ae
reflect.Value.call(0x3a8a20, 0x461d78, 0x13, 0x423d17, 0x4, 0xc4201278c8, 0x1, 0x1, 0x770e8, 0x418f80, ...)
       	/usr/local/Cellar/go/1.7/libexec/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x3a8a20, 0x461d78, 0x13, 0xc4201278c8, 0x1, 0x1, 0x0, 0x138, 0x138)
       	/usr/local/Cellar/go/1.7/libexec/src/reflect/value.go:302 +0xa4
github.com/leancloud/lean-cli/lean/vendor/github.com/codegangsta/cli.HandleAction(0x3a8a20, 0x461d78, 0xc4200a4640, 0x0, 0x0)
       	/private/tmp/lean-cli-20160825-86020-ielkme/lean-cli-0.2.0/src/github.com/leancloud/lean-cli/lean/vendor/github.com/codegangsta/cli/app.go:485 +0x1e0
github.com/leancloud/lean-cli/lean/vendor/github.com/codegangsta/cli.Command.Run(0x4249ef, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x42feb6, 0x21, 0x0, ...)
       	/private/tmp/lean-cli-20160825-86020-ielkme/lean-cli-0.2.0/src/github.com/leancloud/lean-cli/lean/vendor/github.com/codegangsta/cli/command.go:186 +0xc2b
github.com/leancloud/lean-cli/lean/vendor/github.com/codegangsta/cli.(*App).Run(0xc4200fe000, 0xc42000c280, 0x2, 0x2, 0x0, 0x0)
       	/private/tmp/lean-cli-20160825-86020-ielkme/lean-cli-0.2.0/src/github.com/leancloud/lean-cli/lean/vendor/github.com/codegangsta/cli/app.go:239 +0x611
main.main()
       	/private/tmp/lean-cli-20160825-86020-ielkme/lean-cli-0.2.0/src/github.com/leancloud/lean-cli/lean/main.go:121 +0x400
```

**Comment by idy** [comment]
`lean login` 及 `lean upload` 都可以正常执行

**Comment by aisk** [comment]
您好，发现是项目目录结构不符合云引擎项目目录，触发了这个异常。问题已经修复，但是依然需要您修改自己的目录结构。
